import san1 from "./assets/sandwich1.jpg";
import a1 from "./assets/a1.jpg";
import a2 from "./assets/a2.jpg";
import a3 from "./assets/a3.jpg";
import a4 from "./assets/a4.jpg";
import a5 from "./assets/a5.jpg";
import a from "./assets/a.jpg";
import b from "./assets/b.jpg";
import c from "./assets/c.jpg";
import d from "./assets/d.jpg";
import e from "./assets/e.jpg";
import f from "./assets/f.jpg";
import g from "./assets/g.jpg";
import h from "./assets/h.jpg";
import i from "./assets/i.jpg";
import j from "./assets/j.jpg";
import k from "./assets/k.jpg";
import l from "./assets/l.jpg";
import m from "./assets/m.jpg";
import n from "./assets/n.jpg";
import o from "./assets/o.jpg";
import p from "./assets/p.jpg";
import q from "./assets/q.jpg";
import r from "./assets/r.jpg";
import t from "./assets/t.jpg";
import a6 from "./assets/a6.jpg";
import a7 from "./assets/a7.jpg";
import a8 from "./assets/a8.jpg";
import a9 from "./assets/a9.jpg";
import a10 from "./assets/a10.jpg";
import a11 from "./assets/a11.jpg";
import a12 from "./assets/a12.jpg";
import a13 from "./assets/a13.jpg";
import a14 from "./assets/a14.jpg";
import a15 from "./assets/a15.jpg";
import a16 from "./assets/a16.jpg";
import a17 from "./assets/a17.jpg";
import a18 from "./assets/a18.jpg";
import a19 from "./assets/a19.jpg";
import a21 from "./assets/a21.jpg";

const foodItems = [
  {
    id: 1,
    name: "L'express",
    description:
      "Café ou Café crème ou thé à la menthe + Jus d'orange + trois 3 Viennoiserie",
    price: 28,
    image: null,
    category: "petit dejeuner",
  },
  {
    id: 139,
    name: "Brunche la brioche",
    description:
      "",
    price: 28,
    image: l,
    category: "petit dejeuner",
  },
  {
    id: 2,
    name: "Continental",
    description:
      "Café ou Café crème ou the à la menthe Jus d'orange + pain olives noires + huile olive + Jben + 2 œufi",
    price: 36,
    image: null,
    category: "petit dejeuner",
  },
  {
    id: 3,
    name: "Beldi",
    description:
      "Café ou Café crème ou thé à la menthe + Jus d'orange + Rghayef + harcha + baghrir + miel + beure + Amlou + fromage blanc + olives noires",
    price: 38,
    image: m,
    category: "petit dejeuner",
  },
  {
    id: 4,
    name: "Fassi",
    description:
      "Café ou Café crème ou the à la menthe Jus d'orange + Khlie 2 oeufs, olives noires, Miel, Fromages blanc, gâteaux marocains (Fakas, Kaaba, Ghraïba)",
    price: 45,
    image: null,
    category: "petit dejeuner",
  },
  {
    id: 5,
    name: "Espagnol",
    description:
      "Café ou Café crème ou thé à la menthe + Jus d'orange + Tortia Espagnol, Toast au Fromage Dinde Fumée, tomate. Yaourt granola",
    price: 42,
    image: null,
    category: "petit dejeuner",
  },
  {
    id: 6,
    name: "Gourmand",
    description:
      "Café ou Café crème ou thé à la menthe + Jus d'orange + 2 pancakes nutella 2 œufs + Pain (miel, fromage blanc, olives) yaourt",
    price: 42,
    image: k,
    category: "petit dejeuner",
  },
  {
    id: 7,
    name: "Enfant",
    description:
      "Chocolat chaud + jus d'orange + Cornflex + 2 pancakes Nutella",
    price: 25,
    image: null,
    category: "petit dejeuner",
  },
  {
    id: 8,
    name: "La Brioche",
    description:
      "Café ou Café crème ou thé à la menthe + Jus d'orange + 2 merguez 2 croquettes + 2 oeuf + Toast Avocat Dinde fumée + Fromage Blanc Miel, olives noires + Salade de fruit + Crêpe Nutella + yaourt",
    price: 59,
    image: null,
    category: "petit dejeuner",
  },
  {
    id: 9,
    name: "Café gourmand",
    description: "Café + (Fakas, Kaaba, Ghraiba)",
    price: 23,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 10,
    name: "Expresso",
    description: null,
    price: 13,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 11,
    name: "Double expresso",
    description: null,
    price: 16,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 12,
    name: "Café crème",
    description: null,
    price: 14,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 13,
    name: "cappuccin",
    description: null,
    price: 20,
    image: a8,
    category: " boissons chaudes",
  },
  {
    id: 14,
    name: "The marocain",
    description: null,
    price: 14,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 15,
    name: "Chocolat chaud",
    description: null,
    price: 19,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 16,
    name: "Chocolat à l'ancienne",
    description: null,
    price: 28,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 17,
    name: "Café américain",
    description: null,
    price: 18,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 18,
    name: "Verveine",
    description: null,
    price: 13,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 19,
    name: "Lait froid ou chaud",
    description: null,
    price: 12,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 20,
    name: "Mocka",
    description: null,
    price: 18,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 21,
    name: "Machiato",
    description: "(vanille, caramelnoisettes)",
    price: 18,
    image: null,
    category: " boissons chaudes",
  },
  {
    id: 22,
    name: "Ice coffee (Chocolat, American)",
    description: null,
    price: 24,
    image: null,
    category: "Ice coffee",
  },
  {
    id: 23,
    name: "Ice coffee (Vanille, Tonic)",
    description: null,
    price: 22,
    image: a10,
    category: "Ice coffee",
  },
  {
    id: 24,
    name: "Ice cappuccino",
    description: null,
    price: 28,
    image: null,
    category: "Ice coffee",
  },
  {
    id: 124,
    name: "Ice Cofee orange",
    description: null,
    price: 28,
    image: a21,
    category: "Ice coffee",
  },
  {
    id: 25,
    name: "Ice coffee La Brioche",
    description: null,
    price: 28,
    image: null,
    category: "Ice coffee",
  },
  {
    id: 26,
    name: "Ice tea (Citron, Fruit rouge, Piche)",
    description: null,
    price: 14,
    image: null,
    category: "Ice coffee",
  },
  {
    id: 27,
    name: "Smoothie cobano (Ananas, Banane, Fraise)",
    description: null,
    price: 28,
    image: a17,
    category: "boissons fraîches",
  },
  {
    id: 28,
    name: "Smoothie pina colada (Aranas, lait coco)",
    description: null,
    price: 28,
    image: null,
    category: "boissons fraîches",
  },
  {
    id: 29,
    name: "Smoothie sweet (Mangue, menthe, Orange, Citron)",
    description: null,
    price: 28,
    image: null,
    category: "boissons fraîches",
  },
  {
    id: 30,
    name: "Smoothie paradise (Kiwi, Mangue, Banane)",
    description: null,
    price: 28,
    image: a11,
    category: "boissons fraîches",
  },
  {
    id: 31,
    name: "L'ambassadeur La Brioche",
    description: null,
    price: 28,
    image: a6,
    category: "boissons fraîches",
  },
  {
    id: 32,
    name: "Mojito bleu corason",
    description: null,
    price: 28,
    image: a7,
    category: "boissons fraîches",
  },
  {
    id: 119,
    name: "Mojito fruit rouge",
    description: null,
    price: 28,
    image: a19,
    category: "boissons fraîches",
  },
  {
    id: 33,
    name: "Mojito La Brioche",
    description: null,
    price: 28,
    image: null,
    category: "boissons fraîches",
  },
  {
    id: 34,
    name: "Orange",
    description: null,
    price: 17,
    image: null,
    category: "Les jus",
  },
  {
    id: 35,
    name: "Citron",
    description: null,
    price: 16,
    image: null,
    category: "Les jus",
  },
  {
    id: 36,
    name: "Fraise",
    description: null,
    price: 20,
    image: null,
    category: "Les jus",
  },
  {
    id: 37,
    name: "Avocat",
    description: null,
    price: 20,
    image: null,
    category: "Les jus",
  },
  {
    id: 38,
    name: "Orange et mangue",
    description: null,
    price: 25,
    image: null,
    category: "Les cocktails",
  },
  {
    id: 39,
    name: "Orange et ananas",
    description: null,
    price: 26,
    image: null,
    category: "Les cocktails",
  },
  {
    id: 40,
    name: "Orange et Kiwi",
    description: null,
    price: 25,
    image: null,
    category: "Les cocktails",
  },
  {
    id: 41,
    name: "Redlove (Betterave, Mangue, Citron)",
    description: null,
    price: 32,
    image: null,
    category: "Los Detox",
  },
  {
    id: 42,
    name: "Santé (Kiwi, Concombre, Gingembre, Orange)",
    description: null,
    price: 32,
    image: null,
    category: "Los Detox",
  },
  {
    id: 43,
    name: "Exotique (Ananas, Orange, Carotte, Citron)",
    description: null,
    price: 32,
    image: null,
    category: "Los Detox",
  },
  {
    id: 44,
    name: "César",
    description:
      "Laitue, poulet, croûtons de pain, fromage parmesan, sauce césar, tomates cerises",
    price: 35,
    image: null,
    category: "Salades",
  },
  {
    id: 45,
    name: "Italienne",
    description:
      "Pâte, dinde fumée, fromage rouge, maïs, thon, poivrons, sauce maison",
    price: 49,
    image: null,
    category: "Salades",
  },
  {
    id: 46,
    name: "Niçoise",
    description:
      "Laitue, tomates, carottes, pomme de terre, betterave, haricots verts, thon, concombre, riz, oeufs, mayonnaise",
    price: 35,
    image: null,
    category: "Salades",
  },
  {
    id: 47,
    name: "La Brioche",
    description:
      "2 Pièces crevettes royales, mangue, ananas, avocat, maïs, noisette, surimi, calamar, fromage rouge, sauce pesto",
    price: 65,
    image: null,
    category: "Salades",
  },
  {
    id: 48,
    name: "Bolognaise",
    description: "Sauce tomate, viande hachée, fromage parmesan",
    price: 49,
    image: h,
    category: "Pâtes",
  },
  {
    id: 49,
    name: "Poulet Champignons",
    description: "Poulet, champignons de paris, sauce champignons, parmesan",
    price: 45,
    image: e,
    category: "Pâtes",
  },
  {
    id: 50,
    name: "Carbonara",
    description: "Dinde fumée, parmesan, crème, jaune d'œuf",
    price: 49,
    image: g,
    category: "Pâtes",
  },
  {
    id: 51,
    name: "La Brioche",
    description:
      "Calamar, crevettes, 2 pièces crevettes royales, parmesan, moule, crème",
    price: 69,
    image: j,
    category: "Pâtes",
  },
  {
    id: 52,
    name: "Lasagne classique italienne",
    description: null,
    price: 55,
    image: f,
    category: "Pâtes",
  },
  {
    id: 53,
    name: "Fruits De Mer",
    description: null,
    price: 75,
    image: i,
    category: "Risotto",
  },
  {
    id: 54,
    name: "Poulet champignons",
    description: null,
    price: 55,
    image: null,
    category: "Risotto",
  },
  {
    id: 55,
    name: "Quatre Fromages",
    description: null,
    price: 65,
    image: null,
    category: "Risotto",
  },
  {
    id: 56,
    name: "Burger Américain",
    description:
      "Laitue, tomate, oignon caramélisé, fromage cheddar, steak haché, cornichon",
    price: 30,
    image: a,
    category: "Burger",
  },
  {
    id: 58,
    name: "Burger La Brioche",
    description:
      "Laitue, tomate, oignon caramélisé, double steak haché, fromage cheddar, Pesto, dinde fumée, œuf, extra sauce fromagère",
    price: 69,
    image: b,
    category: "Burger",
  },
  {
    id: 59,
    name: "Emincé de Poulet",
    description: null,
    price: 65,
    image: a1,
    category: "Plats",
  },
  {
    id: 60,
    name: "Emincé de Boeuf",
    description: null,
    price: 79,
    image: null,
    category: "Plats",
  },
  {
    id: 61,
    name: "Filet de Boeuf La Brioche",
    description: null,
    price: 95,
    image: null,
    category: "Plats",
  },
  {
    id: 62,
    name: "Poulet Crispy à la Milanaise",
    description: null,
    price: 69,
    image: null,
    category: "Plats",
  },
  {
    id: 63,
    name: "Poulet Crunchy",
    description: null,
    price: 49,
    image: a5,
    category: "Plats",
  },
  {
    id: 64,
    name: "Brochettes de Poulet",
    description: null,
    price: 49,
    image: null,
    category: "Plats",
  },
  {
    id: 65,
    name: "Brochettes de Boeufs",
    description: null,
    price: 69,
    image: null,
    category: "Plats",
  },
  {
    id: 66,
    name: "Brochettes de Viande hachée",
    description: null,
    price: 55,
    image: null,
    category: "Plats",
  },
  {
    id: 67,
    name: "Brochettes Merguez",
    description: null,
    price: 55,
    image: null,
    category: "Plats",
  },
  {
    id: 68,
    name: "Brochettes Mixtes",
    description: "Merguez, viande hachée, poulet, boeuf",
    price: 80,
    image: null,
    category: "Plats",
  },
  {
    id: 69,
    name: "Margarita",
    description: null,
    price: 28,
    image: t,
    category: "Pizzas",
  },
  {
    id: 70,
    name: "Thon",
    description: null,
    price: 35,
    image: q,
    category: "Pizzas",
  },
  {
    id: 71,
    name: "Viande hachée",
    description: null,
    price: 38,
    image: o,
    category: "Pizzas",
  },
  {
    id: 72,
    name: "4 fromages",
    description: null,
    price: 45,
    image: n,
    category: "Pizzas",
  },
  {
    id: 73,
    name: "Quatre saisons",
    description: null,
    price: 49,
    image: r,
    category: "Pizzas",
  },
  {
    id: 74,
    name: "Fruit de mer La Brioche",
    description: null,
    price: 65,
    image: p,
    category: "Pizzas",
  },
  {
    id: 75,
    name: "Viande hachée",
    description: null,
    price: 28,
    image: d,
    category: "Sandwichs",
  },
  {
    id: 76,
    name: "Sandwich poulet mariné fromage",
    description: null,
    price: 26,
    image: san1,
    category: "Sandwichs",
  },
  {
    id: 77,
    name: "Thon",
    description: null,
    price: 22,
    image: null,
    category: "Sandwichs",
  },
  {
    id: 78,
    name: "Merguez",
    description: null,
    price: 30,
    image: null,
    category: "Sandwichs",
  },
  {
    id: 79,
    name: "Boeuf",
    description: null,
    price: 55,
    image: null,
    category: "Sandwichs",
  },
  {
    id: 80,
    name: "Poulet Crispy",
    description: null,
    price: 35,
    image: null,
    category: "Sandwichs",
  },
  {
    id: 81,
    name: "La Brioche",
    description: "Poulet, viande hachée, dinde fumée, bœuf, fromage, pesto",
    price: 49,
    image: null,
    category: "Sandwichs",
  },
  {
    id: 82,
    name: "Crevette royale crunchy",
    description: "6 Pièce",
    price: 49,
    image: null,
    category: "Fruits de mer",
  },
  {
    id: 83,
    name: "Calamar crunchy",
    description: "6 Pièce",
    price: 45,
    image: null,
    category: "Fruits de mer",
  },
  {
    id: 84,
    name: "12 pièces Mix",
    description: null,
    price: 79,
    image: null,
    category: "Fruits de mer",
  },
  {
    id: 85,
    name: "Poulet",
    description: null,
    price: 35,
    image: null,
    category: "Pasticcios",
  },
  {
    id: 86,
    name: "Dinde Fumée",
    description: null,
    price: 39,
    image: null,
    category: "Pasticcios",
  },
  {
    id: 87,
    name: "Viande Hachée",
    description: null,
    price: 39,
    image: null,
    category: "Pasticcios",
  },
  {
    id: 88,
    name: "Fruit de Mer",
    description: null,
    price: 49,
    image: null,
    category: "Pasticcios",
  },
  {
    id: 89,
    name: "La Brioche",
    description: null,
    price: 59,
    image: null,
    category: "Pasticcios",
  },
  {
    id: 90,
    name: "Poisson",
    description: null,
    price: 45,
    image: null,
    category: "Pastilla",
  },
  {
    id: 91,
    name: "Poulet Amande",
    description: null,
    price: 40,
    image: null,
    category: "Pastilla",
  },
  {
    id: 92,
    name: "Fromages",
    description: null,
    price: 30,
    image: null,
    category: "Crêpes",
  },
  {
    id: 93,
    name: "Fromage Dinde Fumée",
    description: null,
    price: 35,
    image: null,
    category: "Crêpes",
  },
  {
    id: 94,
    name: "Poulet Champignons",
    description: null,
    price: 35,
    image: a3,
    category: "Crêpes",
  },
  {
    id: 95,
    name: "Crêpe Nutella",
    description: null,
    price: 29,
    image: a12,
    category: "Crêpes",
  },
  {
    id: 96,
    name: "Nutella Banane",
    description: null,
    price: 34,
    image: null,
    category: "Crêpes",
  },
  {
    id: 97,
    name: "La Brioche",
    description:
      "Banane, fraise, kiwi, boule de glace, nutelle, oreo, fruit sec",
    price: 50,
    image: null,
    category: "Crêpes",
  },
  {
    id: 98,
    name: "Milk-shake vanilla",
    description: null,
    price: 25,
    image: null,
    category: "Milk-shakes",
  },
  {
    id: 99,
    name: "Milk-shake chocolat",
    description: null,
    price: 25,
    image: null,
    category: "Milk-shakes",
  },
  {
    id: 100,
    name: "Milk-shake fraise",
    description: null,
    price: 25,
    image: null,
    category: "Milk-shakes",
  },
  {
    id: 101,
    name: "Milk-shake caramel",
    description: null,
    price: 25,
    image: null,
    category: "Milk-shakes",
  },
  {
    id: 102,
    name: "Milk-shake La Brioche (Snickers)",
    description: null,
    price: 28,
    image: null,
    category: "Milk-shakes",
  },
  {
    id: 103,
    name: "Ice cream la brioche",
    description: "Chocolat, vanille, citron, caramel, nougat, fraise",
    price: 26,
    image: a13,
    category: "glaces",
  },
  {
    id: 104,
    name: "Grand Goya",
    description: "Boule de glace, Chaud de café, crème chantilly",
    price: 26,
    image: null,
    category: "glaces",
  },
  {
    id: 105,
    name: "Sidi Ali 50cl, Aïn Saïss 50cl",
    description: null,
    price: 8,
    image: null,
    category: "Les eaux minérales et sodas",
  },
  {
    id: 106,
    name: "Oulmès 50cl",
    description: null,
    price: 12,
    image: null,
    category: "Les eaux minérales et sodas",
  },
  {
    id: 107,
    name: "Soda",
    description: null,
    price: 14,
    image: null,
    category: "Les eaux minérales et sodas",
  },
  {
    id: 108,
    name: "Schweppes citron",
    description: null,
    price: 15,
    image: null,
    category: "Les eaux minérales et sodas",
  },
  {
    id: 109,
    name: "Coca Zero 33cl",
    description: null,
    price: 15,
    image: null,
    category: "Les eaux minérales et sodas",
  },
  {
    id: 110,
    name: "Red bul",
    description: null,
    price: 28,
    image: null,
    category: "Les eaux minérales et sodas",
  },
  {
    id: 111,
    name: "Tiramisu",
    description: null,
    price: 25,
    image: a15,
    category: "Desserts",
  },
  {
    id: 112,
    name: "Tarte Carrote Noisete",
    description: null,
    price: 28,
    image: a16,
    category: "Desserts",
  },
  {
    id: 113,
    name: "Cheesecake",
    description: null,
    price: 25,
    image: a18,
    category: "Desserts",
  },
  {
    id: 114,
    name: "Sansibastian",
    description: null,
    price: 25,
    image: a14,
    category: "Desserts",
  },
  {
    id: 115,
    name: "Cordon bleu",
    description: null,
    price: 75,
    image: a2,
    category: "Plats",
  },
  {
    id: 116,
    name: "Pasticio poulet",
    description: null,
    price: 35,
    image: a4,
    category: "Plats",
  },
  {
    id: 117,
    name: "Burger chicken",
    description:
      "",
    price: 30,
    image: c,
    category: "Burger",
  },
  {
    id: 118,
    name: "Chokolat a l’encien",
    description: null,
    price: 28,
    image: a9,
    category: "boissons fraîches",
  },
];

export default foodItems;
